export const DATA_COMMAND: string[] = [
  "create",
  "update",
  "delete",
  "clear",
  "list",
  "LIST",
  "open desktop",
  "open cloud",
  "open galery",
  "open home",
  "open download",
  "open doc",
  "open images",
  "open music",
  "open videos",
];
